python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/0_chest_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/0_foot_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/0_head_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours	
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/0_jaw_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/0_pancreas_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours	
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/1_beetle_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/1_bonsai_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/1_broccoli_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/1_kingsnake_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/1_pepper_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/2_backpack_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/2_engine_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/2_mount_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/2_present_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/2_teapot_cone --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours

python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/0_chest_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/0_foot_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/0_head_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2	
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/0_jaw_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/0_pancreas_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2	
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/1_beetle_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/1_bonsai_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/1_broccoli_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/1_kingsnake_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/1_pepper_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/2_backpack_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/2_engine_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/2_mount_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/2_present_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/synthetic_dataset/cone_ntrain_25_angle_360/2_teapot_cone --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2

python3 train_ours.py -s data/real_dataset/cone_ntrain_25_angle_360/pine --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/real_dataset/cone_ntrain_25_angle_360/seashell --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2
python3 train_ours.py -s data/real_dataset/cone_ntrain_25_angle_360/walnut --render_backend r2 --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_r2

python3 train_ours.py -s data/real_dataset/cone_ntrain_25_angle_360/pine --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/real_dataset/cone_ntrain_25_angle_360/seashell --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
python3 train_ours.py -s data/real_dataset/cone_ntrain_25_angle_360/walnut --render_backend slang --wandb --densify_scale_threshold 0.08 --densify_grad_threshold 2.0e-5 --lambda_tv 0.08 -m out_newp_ours
